// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmhLJEyaZxdw_3wTtqIiD7V8lTFqkhbOc',
    appId: '1:277918094868:web:ed66b80eae746932613901',
    messagingSenderId: '277918094868',
    projectId: 'app-jam-2889d',
    authDomain: 'app-jam-2889d.firebaseapp.com',
    storageBucket: 'app-jam-2889d.appspot.com',
    measurementId: 'G-W2YDQSREXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG06AvhOq_rIVBEHs9RvY9e-yYilB5UB4',
    appId: '1:277918094868:android:aca2764cf0a3872d613901',
    messagingSenderId: '277918094868',
    projectId: 'app-jam-2889d',
    storageBucket: 'app-jam-2889d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUezvBix_-5EBftZ-FKvEmCPBcb5BSZFI',
    appId: '1:277918094868:ios:554c3ba876c4c35b613901',
    messagingSenderId: '277918094868',
    projectId: 'app-jam-2889d',
    storageBucket: 'app-jam-2889d.appspot.com',
    iosClientId: '277918094868-iumoqdo6jdbck7g3cbdtndlptgj86p57.apps.googleusercontent.com',
    iosBundleId: 'com.example.signinPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUezvBix_-5EBftZ-FKvEmCPBcb5BSZFI',
    appId: '1:277918094868:ios:554c3ba876c4c35b613901',
    messagingSenderId: '277918094868',
    projectId: 'app-jam-2889d',
    storageBucket: 'app-jam-2889d.appspot.com',
    iosClientId: '277918094868-iumoqdo6jdbck7g3cbdtndlptgj86p57.apps.googleusercontent.com',
    iosBundleId: 'com.example.signinPage',
  );
}
